"""
Signal - loads the synthetic CSVs generated by generate_signal_data.py into
Snowflake's SIGNAL_DB.RAW schema, one raw table per CSV.

Run with: python load_to_snowflake.py
Requires SNOWFLAKE_PASSWORD to be set in your environment (same variable
your dbt profile already uses).
"""

import os

import pandas as pd
import snowflake.connector
from snowflake.connector.pandas_tools import write_pandas

# ---------------------------------------------------------------------------
# Connection settings - mirrors your ~/.dbt/profiles.yml "signal" profile,
# except the target schema is RAW instead of DEV. Keeping the raw landing
# zone in its own schema, separate from where dbt builds its models, is
# standard practice: it makes it obvious which tables are untouched source
# data versus which are dbt-managed outputs.
# ---------------------------------------------------------------------------
SNOWFLAKE_ACCOUNT = "HLLJPRL-KJB40198"
SNOWFLAKE_USER = "SPENCERBBRIAN"
SNOWFLAKE_ROLE = "ACCOUNTADMIN"
SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
SNOWFLAKE_DATABASE = "SIGNAL_DB"
SNOWFLAKE_SCHEMA = "RAW"

# CSV filename (without .csv) -> the table name it should land in.
# Uppercase because Snowflake uppercases unquoted identifiers anyway - naming
# them uppercase here avoids any quoting mismatches later in dbt sources.
TABLES = [
    "plans",
    "subscribers",
    "subscription_history",
    "devices",
    "usage_events",
    "support_tickets",
    "ticket_status_history",
]

OUTPUT_DIR = "output"


def get_connection():
    password = os.environ.get("SNOWFLAKE_PASSWORD")
    if not password:
        raise RuntimeError(
            "SNOWFLAKE_PASSWORD is not set in your environment. "
            "Run: export SNOWFLAKE_PASSWORD='your_password' before this script."
        )
    return snowflake.connector.connect(
        account=SNOWFLAKE_ACCOUNT,
        user=SNOWFLAKE_USER,
        password=password,
        role=SNOWFLAKE_ROLE,
        warehouse=SNOWFLAKE_WAREHOUSE,
        database=SNOWFLAKE_DATABASE,
    )


def main():
    conn = get_connection()
    cursor = conn.cursor()

    # Create the RAW schema if it doesn't already exist yet - the database
    # itself (SIGNAL_DB) was created manually earlier, but schemas within it
    # are fine to create from code since they're just organizational, not a
    # security-sensitive boundary like the database was.
    print(f"Ensuring schema {SNOWFLAKE_DATABASE}.{SNOWFLAKE_SCHEMA} exists...")
    cursor.execute(f"CREATE SCHEMA IF NOT EXISTS {SNOWFLAKE_SCHEMA}")

    for table in TABLES:
        csv_path = f"{OUTPUT_DIR}/{table}.csv"
        print(f"Loading {csv_path} -> {SNOWFLAKE_SCHEMA}.{table.upper()} ...")

        df = pd.read_csv(csv_path)

        # write_pandas is Snowflake's own bulk-load helper: it stages the
        # DataFrame as a file internally and COPY INTOs it, which is far
        # faster than inserting row by row. auto_create_table=True means it
        # creates the table (inferring column types from the DataFrame) if
        # it doesn't exist yet. overwrite=True means re-running this script
        # replaces the table's contents rather than appending duplicates -
        # important while we're still iterating on the data generator.
        success, num_chunks, num_rows, _ = write_pandas(
            conn,
            df,
            table_name=table.upper(),
            database=SNOWFLAKE_DATABASE,
            schema=SNOWFLAKE_SCHEMA,
            auto_create_table=True,
            overwrite=True,
            # Without this, write_pandas quotes column names exactly as the
            # DataFrame has them (lowercase) - Snowflake then treats them as
            # case-sensitive quoted identifiers. dbt's SQL uses plain
            # unquoted column names, which Snowflake auto-uppercases before
            # matching - so quoted lowercase columns become invisible to it.
            # quote_identifiers=False makes the table use normal unquoted
            # (uppercased) column names instead, matching what dbt expects.
            quote_identifiers=False,
        )
        status = "OK" if success else "FAILED"
        print(f"  [{status}] {num_rows} rows in {num_chunks} chunk(s)")

    cursor.close()
    conn.close()
    print("\nDone. All tables loaded into SIGNAL_DB.RAW.")


if __name__ == "__main__":
    main()