# Generated by Django 5.1.2 on 2024-10-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_size',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
