# Generated by Django 5.1.2 on 2024-11-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_uploadedfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
