# Generated by Django 5.1.2 on 2024-11-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_folder_size_alter_uploadedfile_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_size',
            field=models.PositiveIntegerField(),
        ),
    ]
