"""
mongo/schemas.py

Reference schemas for the e-commerce analytics pipeline's MongoDB collections.

MongoDB is schemaless, so these are NOT enforced by the database — they exist as:
  1. A single source of truth for what each document should look like
  2. Sample/template documents used by the simulator and seed scripts
  3. Documentation for index design decisions (see DECISIONS.md for rationale)

Collections: events, orders, products, users
"""

from datetime import datetime, timezone
from typing import TypedDict, Literal, Optional


# ---------------------------------------------------------------------------
# events — high-volume raw stream from Kafka. Flat schema, TTL-indexed.
# ---------------------------------------------------------------------------

EventType = Literal[
    "page_view",
    "add_to_cart",
    "remove_from_cart",
    "checkout_started",
    "purchase",
]


class EventMetadata(TypedDict, total=False):
    ip: str
    country: str          # added by geo_enricher
    city: str              # added by geo_enricher
    device_type: str       # added by device_enricher: mobile | desktop | tablet
    browser: str            # added by device_enricher


class EventDocument(TypedDict, total=False):
    _id: object             # ObjectId, auto-generated by MongoDB
    type: EventType
    user_id: str
    session_id: str
    product_id: Optional[str]
    timestamp: str           # ISO 8601 string, e.g. "2024-03-15T14:22:10Z"
    metadata: EventMetadata


EVENT_EXAMPLE: EventDocument = {
    "type": "add_to_cart",
    "user_id": "usr_8f2a3c91",
    "session_id": "sess_9c1d2e44",
    "product_id": "prod_3a7f1b02",
    "timestamp": datetime.now(timezone.utc).isoformat(),
    "metadata": {
        "ip": "192.168.1.42",
        "country": "FR",
        "city": "Lille",
        "device_type": "mobile",
        "browser": "Safari",
    },
}


# ---------------------------------------------------------------------------
# orders — embeds line items, totals, and shipping address as snapshots.
# ---------------------------------------------------------------------------

OrderStatus = Literal[
    "pending",
    "paid",
    "shipped",
    "delivered",
    "refunded",
    "cancelled",
]


class OrderLineItem(TypedDict):
    product_id: str
    name_snapshot: str       # product name at time of purchase
    unit_price: float         # price at time of purchase, never recalculated
    quantity: int


class OrderTotals(TypedDict):
    subtotal: float
    tax: float
    shipping: float
    total: float


class ShippingAddress(TypedDict):
    line1: str
    line2: Optional[str]
    city: str
    postal_code: str
    country: str


class OrderDocument(TypedDict, total=False):
    _id: object
    order_id: str             # human-readable, e.g. "ORD-20240315-0042"
    user_id: str
    items: list[OrderLineItem]
    totals: OrderTotals
    status: OrderStatus
    shipping_address: ShippingAddress
    created_at: str


ORDER_EXAMPLE: OrderDocument = {
    "order_id": "ORD-20240315-0042",
    "user_id": "usr_8f2a3c91",
    "items": [
        {
            "product_id": "prod_3a7f1b02",
            "name_snapshot": "Pro running shoes",
            "unit_price": 89.99,
            "quantity": 1,
        }
    ],
    "totals": {
        "subtotal": 89.99,
        "tax": 18.00,
        "shipping": 5.99,
        "total": 113.98,
    },
    "status": "shipped",
    "shipping_address": {
        "line1": "12 Rue de la Paix",
        "line2": None,
        "city": "Lille",
        "postal_code": "59000",
        "country": "FR",
    },
    "created_at": datetime.now(timezone.utc).isoformat(),
}

# ---------------------------------------------------------------------------
# products — semi-denormalised catalogue. Category embedded, stats DAG-updated.
# ---------------------------------------------------------------------------

class ProductCategory(TypedDict):
    id: str
    name: str


class ProductInventory(TypedDict):
    quantity: int
    reserved: int
    in_stock: bool


class ProductStats(TypedDict):
    views_7d: int
    purchases_7d: int
    conversion_rate: float


class ProductDocument(TypedDict, total=False):
    _id: object
    sku: str
    name: str
    category: ProductCategory
    price: float
    inventory: ProductInventory
    tags: list[str]
    stats: ProductStats          # updated nightly by Airflow DAG


PRODUCT_EXAMPLE: ProductDocument = {
    "sku": "SHOE-RUN-BLK-42",
    "name": "Pro running shoes",
    "category": {"id": "cat_footwear", "name": "Footwear"},
    "price": 89.99,
    "inventory": {"quantity": 143, "reserved": 5, "in_stock": True},
    "tags": ["running", "sale", "new"],
    "stats": {"views_7d": 1420, "purchases_7d": 38, "conversion_rate": 0.027},
}


class RecentOrderSummary(TypedDict):
    order_id: str
    total: float
    status: OrderStatus
    created_at: str


class RFMScore(TypedDict):
    recency_days: int
    frequency: int
    monetary_total: float


class UserDocument(TypedDict, total=False):
    _id: object
    user_id: str
    email: str
    segments: list[str]              # updated nightly by Airflow DAG
    recent_orders: list[RecentOrderSummary]   # rolling window, last 10
    rfm: RFMScore                       # updated nightly by Airflow DAG
    created_at: str


USER_EXAMPLE: UserDocument = {
    "user_id": "usr_8f2a3c91",
    "email": "alex@example.com",
    "segments": ["high_value", "repeat_buyer"],
    "recent_orders": [
        {
            "order_id": "ORD-20240315-0042",
            "total": 113.98,
            "status": "shipped",
            "created_at": datetime.now(timezone.utc).isoformat(),
        }
    ],
    "rfm": {"recency_days": 3, "frequency": 12, "monetary_total": 1847.50},
    "created_at": "2024-01-10T09:00:00Z",
}


# ---------------------------------------------------------------------------
# Allowed value sets — used by validators and Great Expectations suites.
# ---------------------------------------------------------------------------

ALLOWED_EVENT_TYPES: tuple[str, ...] = (
    "page_view",
    "add_to_cart",
    "remove_from_cart",
    "checkout_started",
    "purchase",
)

ALLOWED_ORDER_STATUSES: tuple[str, ...] = (
    "pending",
    "paid",
    "shipped",
    "delivered",
    "refunded",
    "cancelled",
)

ALLOWED_DEVICE_TYPES: tuple[str, ...] = ("mobile", "desktop", "tablet")


# ---------------------------------------------------------------------------
# Collection name constants — import these instead of hardcoding strings.
# ---------------------------------------------------------------------------

COLLECTION_EVENTS = "events"
COLLECTION_ORDERS = "orders"
COLLECTION_PRODUCTS = "products"
COLLECTION_USERS = "users"
COLLECTION_EVENTS_ARCHIVE = "events_archive"