"""
train_isolation_forest.py

Trains an Isolation Forest model on the normal historical transaction data
generated by generate_training_data.py, evaluates it against a small set of
synthetic anomalies, saves the model artifact with joblib, and uploads it to
GCS (fake-gcs-server locally, real GCS when deployed).

Isolation Forest works by randomly partitioning the feature space into trees.
Normal points require many partitions to isolate (they cluster with others);
anomalies require very few (they sit alone). The model outputs an anomaly
score per record: the closer to -1, the more anomalous; close to +1 is normal.

Run:
    cd ml
    python train_isolation_forest.py              # uploads to fake-gcs-server
    python train_isolation_forest.py --use-real-gcs  # uploads to real GCS
"""

import argparse
import csv
import os
import sys
import tempfile

import joblib
import numpy as np
from sklearn.ensemble import IsolationForest
from sklearn.metrics import classification_report

# Allow importing feature_engineering from the same ml/ folder
sys.path.append(os.path.dirname(__file__))
from feature_engineering import engineer_features, features_to_vector, FEATURE_NAMES  # noqa: E402

# Allow importing reference data helpers from producer/
sys.path.append(os.path.join(os.path.dirname(__file__), "..", "producer"))
from generate_reference_data import VENDOR_CATEGORIES  # noqa: E402

from dotenv import load_dotenv  # noqa: E402

load_dotenv(os.path.join(os.path.dirname(__file__), "..", ".env.local"))

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

TRAINING_DATA_PATH = os.path.join(os.path.dirname(__file__), "training_data.csv")
MODEL_FILENAME = "isolation_forest_v1.joblib"

# GCS config — mirrors the split used in the producer
LOCAL_GCS_ENDPOINT = os.getenv("STORAGE_EMULATOR_HOST", "http://localhost:4443")
REAL_PROJECT_ID = os.getenv("REAL_PROJECT_ID", "portfolio-analytics-499108")
LOCAL_PROJECT_ID = os.getenv("LOCAL_PROJECT_ID", "local-dev-project")
MODEL_BUCKET = os.getenv("MODEL_ARTIFACT_BUCKET", "b2b-spend-models")

# Isolation Forest hyperparameters
# contamination: the proportion of outliers we expect in the training data.
# Since we generated purely normal data, this should be very low — we set
# 0.01 (1%) to account for the fact that even "normal" generated data has
# some statistical outliers at the tails of the distribution.
CONTAMINATION = 0.01
N_ESTIMATORS = 100  # number of trees — 100 is a solid default
RANDOM_STATE = 42


# ---------------------------------------------------------------------------
# Load training data
# ---------------------------------------------------------------------------

def load_training_data(path: str) -> tuple[np.ndarray, list[dict]]:
    """
    Read training_data.csv, run feature engineering on each row, and return:
        - X: numpy array of shape (n_samples, n_features)
        - raw_rows: the original dicts, kept for reference/debugging
    """
    raw_rows = []
    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            raw_rows.append(row)

    feature_vectors = []
    skipped = 0
    for row in raw_rows:
        try:
            features = engineer_features(row)
            feature_vectors.append(features_to_vector(features))
        except Exception as e:
            skipped += 1
            if skipped <= 3:
                print(f"  ⚠️  Skipped row due to error: {e}")

    if skipped:
        print(f"  Skipped {skipped} rows total during feature engineering.")

    X = np.array(feature_vectors)
    return X, raw_rows


# ---------------------------------------------------------------------------
# Build synthetic anomaly test set for sanity check
# ---------------------------------------------------------------------------

def build_test_set(raw_rows: list[dict]) -> tuple[np.ndarray, list[int]]:
    """
    Build a small labelled test set by:
    - Taking 200 random normal rows from the training data (label=0)
    - Synthesising 50 anomalous rows (label=1) by modifying normal rows

    This is a sanity check, not a rigorous benchmark — the model was trained
    on data generated by the same process, so high performance here doesn't
    mean it'll catch every anomaly in the wild. Be upfront about this.
    """
    import random
    import math
    from datetime import datetime, timezone

    normal_sample = random.sample(raw_rows, min(200, len(raw_rows)))
    anomaly_rows = []

    for row in random.sample(raw_rows, 50):
        anomaly_type = random.choice(["spend_spike", "off_hours", "high_amount_ratio"])
        modified = dict(row)

        if anomaly_type == "spend_spike":
            # 15x the normal amount — well outside the training distribution
            modified["amount_usd"] = str(float(row["amount_usd"]) * 15)

        elif anomaly_type == "off_hours":
            # 3am on a Sunday — highly unusual for B2B
            ts = datetime.now(timezone.utc).replace(hour=3, minute=0)
            # Roll to Sunday (weekday=6)
            while ts.weekday() != 6:
                ts = ts.replace(day=ts.day + 1)
            modified["timestamp"] = ts.isoformat()
            modified["amount_usd"] = str(float(row["amount_usd"]) * 8)

        elif anomaly_type == "high_amount_ratio":
            # Amount equal to the full monthly baseline — one transaction
            # consuming the entire month's budget is clearly anomalous
            modified["amount_usd"] = row["baseline_monthly_spend"]

        anomaly_rows.append(modified)

    test_rows = normal_sample + anomaly_rows
    labels = [0] * len(normal_sample) + [1] * len(anomaly_rows)

    feature_vectors = []
    valid_labels = []
    for row, label in zip(test_rows, labels):
        try:
            features = engineer_features(row)
            feature_vectors.append(features_to_vector(features))
            valid_labels.append(label)
        except Exception:
            pass

    X_test = np.array(feature_vectors)
    return X_test, valid_labels


# ---------------------------------------------------------------------------
# Upload model artifact to GCS
# ---------------------------------------------------------------------------

def upload_model(model_path: str, use_real_gcs: bool) -> None:
    """
    Upload the saved model artifact to GCS.
    Uses fake-gcs-server locally, real GCS when --use-real-gcs is passed.
    The google-cloud-storage client reads STORAGE_EMULATOR_HOST automatically
    to redirect traffic to the local fake server — same pattern as the
    Pub/Sub emulator and PUBSUB_EMULATOR_HOST.
    """
    from google.cloud import storage

    if use_real_gcs:
        os.environ.pop("STORAGE_EMULATOR_HOST", None)
        client = storage.Client(project=REAL_PROJECT_ID)
        bucket_name = os.getenv(
            "MODEL_ARTIFACT_BUCKET", "b2b-rtsg-model-artifacts-spencer"
        )
        print(f"☁️  Uploading to REAL GCS bucket: {bucket_name}")
    else:
        client = storage.Client(
            project=LOCAL_PROJECT_ID,
            client_options={"api_endpoint": LOCAL_GCS_ENDPOINT},
        )
        bucket_name = MODEL_BUCKET
        print(f"🧪 Uploading to LOCAL fake-gcs-server bucket: {bucket_name}")

    # Get or create the bucket
    try:
        bucket = client.get_bucket(bucket_name)
    except Exception:
        bucket = client.create_bucket(bucket_name)
        print(f"  Created bucket '{bucket_name}'.")

    blob = bucket.blob(MODEL_FILENAME)
    blob.upload_from_filename(model_path)
    print(f"✅ Uploaded '{MODEL_FILENAME}' to gs://{bucket_name}/{MODEL_FILENAME}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(use_real_gcs: bool) -> None:
    # 1. Load training data
    print(f"Loading training data from {TRAINING_DATA_PATH}...")
    X_train, raw_rows = load_training_data(TRAINING_DATA_PATH)
    print(f"  Loaded {X_train.shape[0]} rows × {X_train.shape[1]} features.")
    print(f"  Features: {FEATURE_NAMES}\n")

    # 2. Train
    print(f"Training Isolation Forest (n_estimators={N_ESTIMATORS}, "
          f"contamination={CONTAMINATION})...")
    model = IsolationForest(
        n_estimators=N_ESTIMATORS,
        contamination=CONTAMINATION,
        random_state=RANDOM_STATE,
        n_jobs=-1,  # use all available CPU cores
    )
    model.fit(X_train)
    print("  Training complete.\n")

    # 3. Sanity check against synthetic anomalies
    print("Running sanity check against synthetic anomalies...")
    X_test, y_true = build_test_set(raw_rows)

    # Isolation Forest predict() returns: 1 = normal, -1 = anomaly
    # We convert to: 0 = normal, 1 = anomaly to match our labels
    raw_preds = model.predict(X_test)
    y_pred = [1 if p == -1 else 0 for p in raw_preds]

    print("\nClassification report (sanity check — not a formal benchmark):")
    print(classification_report(y_true, y_pred, target_names=["normal", "anomaly"]))

    # Also show raw anomaly scores for intuition
    scores = model.score_samples(X_test)
    normal_scores = [s for s, l in zip(scores, y_true) if l == 0]
    anomaly_scores = [s for s, l in zip(scores, y_true) if l == 1]
    print(f"Mean anomaly score — normal rows:  {np.mean(normal_scores):.4f}")
    print(f"Mean anomaly score — anomaly rows: {np.mean(anomaly_scores):.4f}")
    print("(More negative = more anomalous. Anomaly rows should score lower.)\n")

    # 4. Save model artifact
    with tempfile.NamedTemporaryFile(
        suffix=".joblib", delete=False
    ) as tmp:
        tmp_path = tmp.name

    joblib.dump(model, tmp_path)

    local_artifacts_dir = os.path.join(os.path.dirname(__file__), "model_artifacts")
    os.makedirs(local_artifacts_dir, exist_ok=True)
    local_path = os.path.join(local_artifacts_dir, MODEL_FILENAME)
    joblib.dump(model, local_path)
    print(f"📁 Local copy saved to {local_path}")

    # 5. Upload to GCS (local fake or real)
    upload_model(tmp_path, use_real_gcs=use_real_gcs)

    # Clean up temp file
    os.unlink(tmp_path)
    print("\n🎉 Phase 3 complete. Model artifact is ready for the Beam pipeline.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train Isolation Forest model")
    parser.add_argument(
        "--use-real-gcs",
        action="store_true",
        help="Upload model artifact to real GCS instead of local fake-gcs-server",
    )
    args = parser.parse_args()
    main(use_real_gcs=args.use_real_gcs)