version: 2

sources:
- name: raw
  database: DBT_ANALYTICS
  schema: raw
  tables:
    - name: customers  
      description: Raw customer data loaded from CSV
      columns:
        - name: customer_id
          description: Primary key for customers
          tests:
            - unique
            - not_null
    - name: orders
      description: Raw order data loaded from CSV.
      columns:
        - name: order_id
          description: Primary key for orders.
          tests:
            - unique
            - not_null
        - name: customer_id
          description: Foreign key to customers.
          tests:
            - not_null
            - relationships:
                to: source('raw', 'customers')
                field: customer_id